#!/bin/bash

git stash
git stash branch "feature/${1}"
git add .
git commit -m "separate new feature in a branch"
git push origin --all
CURRENT=$(git rev-parse --abbrev-ref HEAD)
HOSTNAME=$(grep -oP 'repository = "\K[^"]+' Cargo.toml | sed -E 's#^https?://([^/]+)/.*$#\1#' | cut -d : -f 1)
USERNAME=$(grep -oP 'repository = "\K[^"]+' Cargo.toml | sed -E 's#^https?://[^/]+/([^/]+)/.*$#\1#')
PROJECT=$(grep -oP 'repository = "\K[^"]+' Cargo.toml | sed -E 's#^https?://[^/]+/[^/]+/([^/]+)/?$#\1#')

cd continuous/rust && ./scripts-gen "${HOSTNAME}" "$USERNAME" "$PROJECT" "$CURRENT" "4" || exit 1
packer validate . || exit 1
packer build . || exit 1
exit 0