[package]
name = "zuu"
version = "12.0.0"
edition = "2021"
license = "GPL-2.0-or-later"
keywords = ["code", "quality", "production", "certified","git"]
categories = ["development-tools","development-tools::testing"]
readme = "README.md"
authors = ["Willy Micieli"]
repository = "https://github.com/otechdo/zuu"
description = "A program to check your code quality before all commit"

[[bin]]
name = "uninstall_zuu"
path = "src/delete.rs"

[[bin]]
name = "install_zuu"
path = "src/install.rs"



[dependencies]
ansi-escapes = "=0.1.1"
