[package]
name = "zuu"
version = "19.0.1"
edition = "2021"
license = "GPL-3.0"
keywords = ["code", "quality", "production", "certified", "rust"]
categories = ["development-tools", "development-tools::testing"]
readme = "README.md"
authors = ["Willy Micieli"]
repository = "https://github.com/otechdo/zuu"
description = "A program to check your code quality before all commit"
