[package]
name = "zuu"
version = "21.1.1"
edition = "2021"
license = "AGPL-3.0"
categories = ["development-tools", "development-tools::testing"]
readme = "README.md"
authors = ["Willy Micieli"]
repository = "https://github.com/otechdo/zuu"
description = "A program to check your code quality before all commit"
keywords = ["lint", "quality", "prevention", "Maintainability", "optimization"]
[dependencies]
inquire = { version = "0.7.5", features = ["console", "editor"] }
toml = "0.8.19"
