[package]
name = "zuu"
version = "23.0.0"
edition = "2021"
license = "AGPL-3.0"
categories = ["development-tools", "development-tools::testing"]
readme = "README.md"
authors = ["Willy Micieli"]
repository = "https://github.com/otechdo/zuu"
description = "A program to check your code quality before all commit"
keywords = ["lint", "quality", "prevention", "Maintainability", "optimization"]
[dependencies]

[features]
default = ["rust"]
bash = []
c = []
clojure = []
cobol = []
crystal = []
d = []
dart = []
elixir = []
erlang = []
fortran = []
fsharp = []
go = []
groovy = []
haskell = []
java = []
julia = []
kotlin = []
lua = []
matlab = []
nim = []
nodejs = []
objc = []
ocaml = []
perl = []
php = []
python = []
r = []
ruby = []
rust = []
scala = []
swift = []
tcl = []
typescript = []
vhdl = []
vlang = []