[package]
name = "zuu"
version = "22.0.1"
edition = "2021"
license = "AGPL-3.0"
categories = ["development-tools", "development-tools::testing"]
readme = "README.md"
authors = ["Willy Micieli"]
repository = "https://github.com/otechdo/zuu"
description = "A program to check your code quality before all commit"
keywords = ["lint", "quality", "prevention", "Maintainability", "optimization"]
[dependencies]
chrono = "0.4.38"
colored_truecolor = "0.1.0"
indicatif = "0.17.8"
inquire = { version = "0.7.5", features = ["console", "editor"] }
rand = "0.8.5"
toml = "0.8.19"
