[package]
name = "zuu"
version = "23.0.0"
edition = "2021"
license = "AGPL-3.0"
categories = ["development-tools", "development-tools::testing"]
readme = "README.md"
authors = ["Willy Micieli"]
repository = "https://github.com/otechdo/zuu"
description = "A program to check your code quality before all commit"
keywords = ["lint", "quality", "prevention", "Maintainability", "optimization"]
[dependencies]
crossterm = { version = "0.28.1", optional = true }
indicatif = { version = "0.17.8", optional = true }
inquire = { version = "0.7.5", optional = true, features = [
    "console",
    "editor",
] }
ratatui = { version = "0.28.1", features = ["all-widgets"], optional = true }
toml = "0.8.19"

[features]
default = ["ui"]
ui = ["ratatui", "ratatui/all-widgets", "crossterm"]
cli = ["inquire", "indicatif"]
