[package]
name = "zuu"
version = "20.0.0"
edition = "2021"
license = "MIT"
keywords = ["code", "quality", "production", "certified", "rust"]
categories = ["development-tools", "development-tools::testing"]
readme = "README.md"
authors = ["Willy Micieli"]
repository = "https://github.com/otechdo/zuu"
description = "A program to check your code quality before all commit"

[dependencies]
clap = "4.5.16"
