services:
  zuu:
    image: otechdo/zuu:latest
    environment:
      - TESTS=true
      - FORMAT=true
      - LINT=true
      - AUDIT=true
      - LICENSE=true
      - EDITOR=vim
    volumes:
      - .:/app
    command:
      - rust-audit