allow = ["cargo"]
warn = []
forbid = [
    "nursery",
    "perf",
    "complexity",
    "style",
    "pedantic",
    "suspicious",
    "correctness",
]
before-cargo = []
cargo = [
    "verify-project",
    "check --all-targets --profile=test",
    "audit",
    "test -j 4 --no-fail-fast -- --show-output",
    "fmt --check",
    "outdated",
]
after-cargo = []
