#!/usr/bin/env bash

if [ -n "$GIT_DIR" ]
then
  unset GIT_DIR
fi

tput civis
LINES=$(tput lines)
COLUMNS=$(tput cols)
TASKS=('mod verify' 'go build' 'go test -v' 'go vet')

function shutdown() {
  tput cnorm # reset cursor
}
trap shutdown EXIT

function cursorBack() {
  echo -en "\033[$1D"
  # Mac compatible, but goes back to first column always. See comments
  #echo -en "\r"
}

function run() {
  output "$1"
  if ! $x  ;
  then
      tput cnorm
      exit 1
  fi
}

function output {
    local b=""
    for (( i = 0; i < (COLUMNS); i++ ))
    do
        b+="="
    done
    tput cuf 0
    printf "\n%s\n" "$b"
    printf "\n%*s\n" $(((${#1}+COLUMNS)/2)) "$1"
    tput cuf 0
    printf "\n%s\n\n" "$b"
}

for x in "${TASKS[@]}"
do
  run "$x"
done

output "The code can be committed"
exit 0
