name: zuu
on:
  push:
    branches: [ "master" , "develop" , "main" ]
  pull_request:
    branches: [ "master" , "develop" , "main"  ]
env:
  CARGO_TERM_COLOR: always
  TERM: xterm-256color
jobs:
  zuu:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: deps
      run: cargo install cargo-audit zuu 
    - name: zuu
      run: git clone https://github.com/otechdo/zuu . && cd zuu &&  git checkout "${GITHUB_REF##*/}"  && zuu
