name: zuu
on:
  push:
    branches: [ "master" , "develop" , "main" ]
  pull_request:
    branches: [ "master" , "develop" , "main"  ]
env:
  CARGO_TERM_COLOR: always
  TERM: xterm-256color
jobs:
  zuu:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-22.04, ubuntu-20.04, macos-latest, macos-13, macos-12 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: deps
        run:  cargo install cargo-audit cargo-auditable cargo-deny cargo-outdated
      - name: installation
        run:  cargo install zuu --no-default-features --features cli
      - name: zuu
        run:  git checkout "${GITHUB_REF##*/}" && zuu
