name: zuu
on:
  push:
    branches: [ "master" , "develop" , "main" ]
  pull_request:
    branches: [ "master" , "develop" , "main"  ]
env:
  CARGO_TERM_COLOR: always
  TERM: xterm-256color
jobs:
  zuu:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        toolchain:
          - stable
          - beta
          - nightly
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: deps
      run: cargo install cargo-audit zuu
    - name: zuu
      shell: bash
    - run: |
    	if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
			git clone https://github.com/otechdo/zuu app && cd .\app &&  git checkout "${GITHUB_REF##*/}"  && zuu
		else
			git clone https://github.com/otechdo/zuu app && cd app &&  git checkout "${GITHUB_REF##*/}"  && zuu
		fi
    
